

trigger:
- master
pool:
  #vmInage: ubuntu-latest
  name: 'Github-codespaces-pool'
steps:
  - script: echo Hello, world!
    displayName: 'Run a one-liner script'
  - script: |
      echo This codesace hostname:
      echo
      echo SHOSTNAME
    displayName: 'Run a multi-line script'